export class LinesItem {
  id: number = -1;
  variant_id: number = 0;
  title: string = '';
  quantity: number = 0;
  price: number = 0;
  grams: number = 0;
  sku: number = 0;
  variant_title: string = '';
  vendor: string = '';
  fulfillment_service: string = '';
  product_id: number = 0;
  requires_shipping: boolean = false;
  taxable: boolean = false;
  gift_card: boolean = false;
  name: string = '';
  variant_inventory_management: string = '';
  properties: any = [];
  product_exists: boolean = false;
  fulfillable_quantity: number = 0;
  total_discount: number = 0;
  fulfillment_status: string = '';
  img: string = '';
  tax_lines: any = [];
}
